// CADENCE NUMBER
#define CADENCE_NUMBER_X  10
#define CADENCE_NUMBER_Y 28

// SPEED NUMBER
#define SPEED_NUMBER_X  29
#define SPEED_NUMBER_Y 6
#define SPEED_FONT_SIZE 1

// SPEED IMAGE
#define SPEED_IMAGE_X  1
#define SPEED_IMAGE_Y 6

// TIME NUMBER
#define TIME_NUMBER_X 48 + bars_w
#define TIME_NUMBER_Y 31 + bars_h + 2

// DISTANCE NUMBER
#define DISTANCE_NUMBER_X  10
#define DISTANCE_NUMBER_Y 31 + crankset_h + 2

// ICON SET ROWS
#define ICONSET_ROWS 2

// ICON SET LEFT
#define ICONSET_LEFT_X  3
#define ICONSET_LEFT_Y 27

//ICON SET RIGHT
#define ICONSET_RIGHT_X  47
#define ICONSET_RIGHT_Y 27

// SLEEP TIME THRESHOLD
#define sleepThreshold 30
