// CADENCE NUMBER
#define CADENCE_NUMBER_X 22
#define CADENCE_NUMBER_Y 16

// SPEED NUMBER
#define SPEED_NUMBER_X 38
#define SPEED_NUMBER_Y 3
#define SPEED_FONT_SIZE 1

// SPEED IMAGE
#define SPEED_IMAGE_X 8
#define SPEED_IMAGE_Y 3

// TIME NUMBER
#define TIME_NUMBER_X 28
#define TIME_NUMBER_Y 40

// DISTANCE NUMBER
#define DISTANCE_NUMBER_X 28
#define DISTANCE_NUMBER_Y 24

// ICON SET ROWS
#define ICONSET_ROWS 1

// ICON SET LEFT
#define ICONSET_LEFT_X 18
#define ICONSET_LEFT_Y 15

//ICON SET RIGHT
#define ICONSET_RIGHT_X 18
#define ICONSET_RIGHT_Y 15

// SLEEP TIME THRESHOLD
#define sleepThreshold 10
