


























.build_ano/uno/SPI/src/SPI.cpp.o : /usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src/SPI.cpp
	@echo [93mSPI/src/SPI.cpp[0m
	@mkdir -p .build_ano/uno/SPI/src
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino" -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src/SPI.cpp
include .build_ano/uno/SPI/src/SPI.cpp.d








.build_ano/uno/SPI/libSPI.a : .build_ano/uno/SPI/src/SPI.cpp.o
	@echo [92mLinking libSPI.a[0m
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^








.build_ano/uno/arduino/WInterrupts.c.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c
	@echo [93marduino/WInterrupts.c[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino"   -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c
include .build_ano/uno/arduino/WInterrupts.c.d

.build_ano/uno/arduino/wiring_pulse.c.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c
	@echo [93marduino/wiring_pulse.c[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino"   -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c
include .build_ano/uno/arduino/wiring_pulse.c.d

.build_ano/uno/arduino/wiring.c.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c
	@echo [93marduino/wiring.c[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino"   -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c
include .build_ano/uno/arduino/wiring.c.d

.build_ano/uno/arduino/wiring_shift.c.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c
	@echo [93marduino/wiring_shift.c[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino"   -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c
include .build_ano/uno/arduino/wiring_shift.c.d

.build_ano/uno/arduino/wiring_analog.c.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c
	@echo [93marduino/wiring_analog.c[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino"   -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c
include .build_ano/uno/arduino/wiring_analog.c.d

.build_ano/uno/arduino/hooks.c.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c
	@echo [93marduino/hooks.c[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino"   -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c
include .build_ano/uno/arduino/hooks.c.d

.build_ano/uno/arduino/wiring_digital.c.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c
	@echo [93marduino/wiring_digital.c[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino"   -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c
include .build_ano/uno/arduino/wiring_digital.c.d






.build_ano/uno/arduino/Stream.cpp.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp
	@echo [93marduino/Stream.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino" -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp
include .build_ano/uno/arduino/Stream.cpp.d

.build_ano/uno/arduino/HardwareSerial.cpp.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp
	@echo [93marduino/HardwareSerial.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino" -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp
include .build_ano/uno/arduino/HardwareSerial.cpp.d

.build_ano/uno/arduino/Print.cpp.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp
	@echo [93marduino/Print.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino" -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp
include .build_ano/uno/arduino/Print.cpp.d

.build_ano/uno/arduino/Tone.cpp.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp
	@echo [93marduino/Tone.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino" -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp
include .build_ano/uno/arduino/Tone.cpp.d

.build_ano/uno/arduino/main.cpp.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp
	@echo [93marduino/main.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino" -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp
include .build_ano/uno/arduino/main.cpp.d

.build_ano/uno/arduino/PluggableUSB.cpp.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/PluggableUSB.cpp
	@echo [93marduino/PluggableUSB.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino" -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/PluggableUSB.cpp
include .build_ano/uno/arduino/PluggableUSB.cpp.d

.build_ano/uno/arduino/HardwareSerial2.cpp.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp
	@echo [93marduino/HardwareSerial2.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino" -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp
include .build_ano/uno/arduino/HardwareSerial2.cpp.d

.build_ano/uno/arduino/CDC.cpp.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp
	@echo [93marduino/CDC.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino" -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp
include .build_ano/uno/arduino/CDC.cpp.d

.build_ano/uno/arduino/HardwareSerial3.cpp.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp
	@echo [93marduino/HardwareSerial3.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino" -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp
include .build_ano/uno/arduino/HardwareSerial3.cpp.d

.build_ano/uno/arduino/HardwareSerial1.cpp.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp
	@echo [93marduino/HardwareSerial1.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino" -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp
include .build_ano/uno/arduino/HardwareSerial1.cpp.d

.build_ano/uno/arduino/USBCore.cpp.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp
	@echo [93marduino/USBCore.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino" -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp
include .build_ano/uno/arduino/USBCore.cpp.d

.build_ano/uno/arduino/WMath.cpp.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp
	@echo [93marduino/WMath.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino" -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp
include .build_ano/uno/arduino/WMath.cpp.d

.build_ano/uno/arduino/IPAddress.cpp.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp
	@echo [93marduino/IPAddress.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino" -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp
include .build_ano/uno/arduino/IPAddress.cpp.d

.build_ano/uno/arduino/HardwareSerial0.cpp.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp
	@echo [93marduino/HardwareSerial0.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino" -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp
include .build_ano/uno/arduino/HardwareSerial0.cpp.d

.build_ano/uno/arduino/abi.cpp.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp
	@echo [93marduino/abi.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino" -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp
include .build_ano/uno/arduino/abi.cpp.d

.build_ano/uno/arduino/WString.cpp.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp
	@echo [93marduino/WString.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino" -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp
include .build_ano/uno/arduino/WString.cpp.d

.build_ano/uno/arduino/new.cpp.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp
	@echo [93marduino/new.cpp[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino" -fno-exceptions  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp
include .build_ano/uno/arduino/new.cpp.d






.build_ano/uno/arduino/wiring_pulse.S.o : /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.S
	@echo [93marduino/wiring_pulse.S[0m
	@mkdir -p .build_ano/uno/arduino
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino" -x assembler-with-cpp  -o $@ -c /usr/local/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.S
include .build_ano/uno/arduino/wiring_pulse.S.d



.build_ano/uno/arduino/libarduino.a : .build_ano/uno/arduino/WInterrupts.c.o .build_ano/uno/arduino/wiring_pulse.c.o .build_ano/uno/arduino/wiring.c.o .build_ano/uno/arduino/wiring_shift.c.o .build_ano/uno/arduino/wiring_analog.c.o .build_ano/uno/arduino/hooks.c.o .build_ano/uno/arduino/wiring_digital.c.o .build_ano/uno/arduino/Stream.cpp.o .build_ano/uno/arduino/HardwareSerial.cpp.o .build_ano/uno/arduino/Print.cpp.o .build_ano/uno/arduino/Tone.cpp.o .build_ano/uno/arduino/main.cpp.o .build_ano/uno/arduino/PluggableUSB.cpp.o .build_ano/uno/arduino/HardwareSerial2.cpp.o .build_ano/uno/arduino/CDC.cpp.o .build_ano/uno/arduino/HardwareSerial3.cpp.o .build_ano/uno/arduino/HardwareSerial1.cpp.o .build_ano/uno/arduino/USBCore.cpp.o .build_ano/uno/arduino/WMath.cpp.o .build_ano/uno/arduino/IPAddress.cpp.o .build_ano/uno/arduino/HardwareSerial0.cpp.o .build_ano/uno/arduino/abi.cpp.o .build_ano/uno/arduino/WString.cpp.o .build_ano/uno/arduino/new.cpp.o .build_ano/uno/arduino/wiring_pulse.S.o
	@echo [92mLinking libarduino.a[0m
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^















.build_ano/uno/src/sketch.ino.cpp.o : .build_ano/uno/src/sketch.ino.cpp
	@echo [93msrc/sketch.ino.cpp[0m
	@mkdir -p .build_ano/uno/src
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=182 -DARDUINO_ARCH_AVR -I/usr/local/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/local/share/arduino/hardware/arduino/avr/variants/standard -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI" -I"/usr/local/share/arduino/hardware/arduino/avr/libraries/SPI/src" -I"/usr/local/share/arduino/hardware/arduino/avr/cores/arduino" -fno-exceptions -iquote src  -o $@ -c .build_ano/uno/src/sketch.ino.cpp
include .build_ano/uno/src/sketch.ino.cpp.d















.build_ano/uno/firmware.elf : .build_ano/uno/src/sketch.ino.cpp.o .build_ano/uno/SPI/libSPI.a .build_ano/uno/arduino/libarduino.a
	@echo [92mLinking firmware.elf[0m
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -Wl,-Os -Wl,--gc-sections -o $@ $^ -lm


.build_ano/uno/firmware.hex : .build_ano/uno/firmware.elf
	@echo [92mConverting to firmware.hex[0m
	@/usr/local/share/arduino/hardware/tools/avr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build_ano/uno/src/dependencies.d .build_ano/uno/SPI/dependencies.d .build_ano/uno/arduino/dependencies.d

all : .build_ano/uno/firmware.hex
	@true

